### ISSUE TITLE
`pkgcheck` action fails with AttributeError: 'object' object has no attribute 'KEYWORDS'

### ISSUE THREAD

**Issue by trofi** [pkgcore/pkgcheck-action#13]
The action seems to have started failing yesterday: https://github.com/trofi/nix-guix-gentoo/actions

Action implementation:

```yaml
# https://github.com/pkgcore/pkgcheck-action#example-workflows
name: pkgcheck

on:
  push:
  pull_request:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
```

Example failure from https://github.com/trofi/nix-guix-gentoo/actions/runs/6661329267/job/18113265061 :

```
FAILURE RESULTS
/opt/hostedtoolcache/Python/3.12.0/x64/bin/pkgcheck replay --color y /home/runner/failures.json
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/objects.py", line 87, in _dict
    result = getattr(_defaults, self._attr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'object' object has no attribute 'KEYWORDS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0/x64/bin/pkgcheck", line 5, in <module>
    from pkgcheck.scripts.__init__ import main
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/__init__.py", line 3, in <module>
    from .api import keywords, scan
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/api.py", line 9, in <module>
    from . import objects
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/objects.py", line 198, in <module>
    KEYWORDS = _KeywordsLazyDict("KEYWORDS", ("checks", "results.Result"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/objects.py", line 82, in __init__
    self._dict
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/snakeoil/klass.py", line 203, in __get__
    obj = self.function(instance)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/objects.py", line 89, in _dict
    result = _find_obj_classes(*self._func_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/objects.py", line 51, in _find_obj_classes
    module = import_module(f".{module_name}", "pkgcheck")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/checks/__init__.py", line 10, in <module>
    from .. import addons, base, feeds, runners, sources
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/feeds.py", line 3, in <module>
    from . import base, sources
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/sources.py", line 17, in <module>
    from .bash import ParseTree
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pkgcheck/bash/__init__.py", line 6, in <module>
    from tree_sitter import Language, Parser
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/tree_sitter/__init__.py", line 5, in <module>
    from distutils.ccompiler import new_compiler
ModuleNotFoundError: No module named 'distutils'
Error: The process '/opt/hostedtoolcache/Python/3.12.0/x64/bin/pkgcheck' failed with exit code 1
```

**Comment by trofi** [comment]
Diffing install logs of last successful run and last failing run looks like the only difference is python interpreter version:

```diff
--- good-pkgcheck       2023-10-27 18:49:08.283667439 +0100
+++ bad-pkgcheck        2023-10-27 18:50:40.211237179 +0100
@@ -1,36 +1,35 @@
-  /opt/hostedtoolcache/Python/3.11.6/x64/bin/pip install --upgrade pip
-  Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages (23.3)
+  /opt/hostedtoolcache/Python/3.12.0/x64/bin/pip install --upgrade pip
+  Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages (23.2.1)
```

**Comment by thesamesam** [comment]
Python 3.12 drops its copy of distutils. We could either depend on setuptools still for the bundled copy of tree-sitter-bash (we allow using the system copy but the action doesn't use it) or port away from that too.
