### ISSUE TITLE
python 3.10 breaks pkgcheck

### ISSUE THREAD

**Issue by nabbi** [pkgcore/pkgcheck-action#4]
3.x began installing Python 3.10.0 which is throwing pmaint errors 

There are two forks with comparable workarounds, installing 3.9 instead of 3.x
* [osirisinferi](https://github.com/osirisinferi/pkgcheck-action/commit/354d4b2e5311b88310d0ba56fd7e1410a0947458)
* [nabbi](https://github.com/nabbi/pkgcheck-action/commit/46652d6e3d28b0d2c901ea31dcc623ed2a2d86e4)

```
Sync gentoo repo
  /opt/hostedtoolcache/Python/3.10.0/x64/bin/pmaint sync gentoo
  *** syncing gentoo
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 1348, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1276, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1322, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1271, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1031, in _send_output
      self.send(msg)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 969, in send
      self.connect()
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/http/client.py", line 1448, in connect
      self.sock = self._context.wrap_socket(self.sock,
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ssl.py", line 512, in wrap_socket
      return self.sslsocket_class._create(
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/ssl.py", line 1061, in _create
      self._sslobj = self._context._wrap_socket(
  ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/sync/http.py", line 53, in _sync
      resp = urllib.request.urlopen(req, context=context)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 519, in open
      response = self._open(req, data)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 536, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 496, in _call_chain
      result = func(*args)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 1391, in https_open
      return self.do_open(http.client.HTTPSConnection, req,
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/urllib/request.py", line 1351, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)>
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.10.0/x64/bin/pmaint", line 4, in <module>
      scripts.run(basename(__file__))
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/scripts/__init__.py", line 32, in run
      sys.exit(tool())
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 79, in __call__
      ret = self.main()
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 185, in main
      self.handle_exec_exception(e)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 170, in main
      exitstatus = func(self.options, self.out, self.err)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/scripts/pmaint.py", line 71, in sync_main
      ret = repo.operations.sync(
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/operations/__init__.py", line 69, in _recast_exception_decorator
      return functor(*args, **kwds)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/operations/repo.py", line 146, in _cmd_api_sync
      ret = syncer.sync(**kwargs)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/sync/base.py", line 131, in sync
      return self._sync(verbosity, 1, **kwds)
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pkgcore/sync/http.py", line 55, in _sync
      if e.getcode() == 304: # Not Modified
  AttributeError: 'URLError' object has no attribute 'getcode'
Error: The process '/opt/hostedtoolcache/Python/3.10.0/x64/bin/pmaint' failed with exit code 1
```

**Comment by AndrewAmmerlaan** [comment]
We were having the same issue in `::guru` and `::sci`: 
https://github.com/gentoo/sci/runs/4087197115?check_suite_focus=true

However, as of today the error has changed to:

```
       File "/tmp/tmpqi322ju5_in_process.py", line 363, in <module>
          main()
        File "/tmp/tmpqi322ju5_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/tmpqi322ju5_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          setup(**dict(
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 159, in setup
          return distutils.core.setup(**attrs)
        File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 113, in _add_defaults_python
          self._add_data_files(self._safe_data_files(build_py))
        File "/tmp/pip-build-env-brn6mc8m/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 621, in _safe_data_files
          return build_py.get_data_files_without_manifest()
        File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: get_data_files_without_manifest
```

https://github.com/gentoo/sci/runs/4103754568?check_suite_focus=true

**Comment by thesamesam** [comment]
Fixed by https://github.com/pkgcore/pkgcore/commit/276f3a7686aaa46844903e2387798d36d786a179.

**Comment by arthurzam** [comment]
Looks like it is fixed, but if it reappears, let's create a new issue 😄
