### ISSUE TITLE
pip install pkgcheck fails

### ISSUE THREAD

**Issue by flammie** [pkgcore/pkgcheck-action#5]
I tried to start using this in https://github.com/flammie/flammie-overlay but it fails in pip installing pkgcheck https://github.com/flammie/flammie-overlay/runs/7538103278?check_suite_focus=true , I tried in a venv with same results:
```
$ python -m venv pkgcheck
$ cd pkgcheck/
$ . bin/activate
$  pip install pkgcheck
Collecting pkgcheck
  Downloading pkgcheck-0.10.11.tar.gz (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.1/474.1 KB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools
        Downloading setuptools-63.2.0-py3-none-any.whl (1.2 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.2 MB/s eta 0:00:00
      Collecting chardet
        Downloading chardet-5.0.0-py3-none-any.whl (193 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 KB 6.7 MB/s eta 0:00:00
      Collecting lazy-object-proxy
        Downloading lazy_object_proxy-1.7.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 7.1 MB/s eta 0:00:00
      Collecting lxml
        Downloading lxml-4.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 4.2 MB/s eta 0:00:00
      Collecting pathspec
        Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
      Collecting tree-sitter>=0.19.0
        Downloading tree_sitter-0.20.0.tar.gz (116 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.2/116.2 KB 5.7 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting snakeoil~=0.9.10
        Downloading snakeoil-0.9.10.tar.gz (264 kB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.4/264.4 KB 3.8 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [17 lines of output]
            Traceback (most recent call last):
              File "/tmp/tmp__nukgk7_in_process.py", line 363, in <module>
                main()
              File "/tmp/tmp__nukgk7_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/tmp/tmp__nukgk7_in_process.py", line 130, in get_requires_for_build_wheel
                return hook(config_settings)
              File "/tmp/pip-build-env-o21ixm7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
                return self._get_build_requires(
              File "/tmp/pip-build-env-o21ixm7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
                self.run_setup()
              File "/tmp/pip-build-env-o21ixm7o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
                exec(code, locals())
              File "<string>", line 10, in <module>
              File "/tmp/pip-install-brbg8pcx/snakeoil_d720d790c0bc4e699cddb37b29729708/src/snakeoil/dist/distutils_extensions.py", line 54, in <module>
                raise ImportError('this module is only meant to be imported in setup.py scripts')
            ImportError: this module is only meant to be imported in setup.py scripts
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      WARNING: You are using pip version 22.0.4; however, version 22.2 is available.
      You should consider upgrading via the '/home/flammie/tmp/pkgcheck/bin/python -m pip install --upgrade pip' command.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: You are using pip version 22.0.4; however, version 22.2 is available.
You should consider upgrading via the '/home/flammie/tmp/pkgcheck/bin/python -m pip install --upgrade pip' command.
```

I am a new user so it is possible I did something very basic wrong.

**Comment by arthurzam** [comment]
Can you please retry, as we had big problems with the whole stack installing through pip, which were all fixed hopefully.

**Comment by flammie** [comment]
I think it has worked, I get an actual error report in the ci run.
